name: Build NwPluginAPI based plugin
description: Builds, prepares artifacts and optionally runs tests for NwPluginAPI based plugin.
author: Adam Szerszenowicz (https://github.com/Pogromca-SCP)

branding:
  icon: aperture
  color: gray-dark

inputs:
  plugin-name:
    description: Name of main plugin assembly to package.
    required: true

  refs-variable:
    desctiption: Name of game files references environment variable used in the project.
    default: 
    required: false

  depot-downloader-version:
    description: Depot downloader version to use for game files download.
    default: 2.5.0
    required: false

  run-tests:
    description: Whether or not the tests should be run for the project.
    default: true
    required: false

  initial-test-runs:
    description: Amount of initial test runs.
    default: 3
    required: false

  dependencies:
    description: List of assembly names to add into dependencies.zip file.
    default: '@()'
    required: false

  bin-path:
    description: Binary files path pattern to use '$' is replaced with assembly/project name.
    default: /$/bin/Release/net48/$
    required: false

runs:
  using: composite
  steps:
    - name: Build project
      shell: pwsh 
      run: ${{ github.action_path }}/src/build_project.ps1 -referencesVariable ${{ inputs.refs-variable }} -depotDownloaderVersion ${{ inputs.depot-downloader-version }}

    - name: Run initial tests
      if: ${{ inputs.runTests }}
      shell: pwsh
      run: ${{ github.action_path }}/src/init_tests.ps1 -referencesVariable ${{ inputs.refs-variable }} -initialRuns ${{ inputs.initial-test-runs }}

    - name: Run tests
      if: ${{ inputs.runTests }}
      shell: pwsh
      run: dotnet test --no-build --verbosity normal

    - name: Prepare artifacts
      shell: pwsh
      run: ${{ github.action_path }}/src/prepare_artifacts.ps1 -pluginName ${{ inputs.plugin-name }} -workspacePath ${{ github.workspace }} -binPathPattern ${{ inputs.bin-path }} -dependencies ${{ inputs.dependencies }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ inputs.plugin-name }}
        path: D:/plugin/Artifacts
