name: Update major tag

on:
  release:
    types: [published, edited]

jobs:
  update-tag:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
