name: Update major tag

on:
  release:
    types: [published]

jobs:
  update-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
